apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
data:
  PORT: "8080"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode yes
    requirepass admin12345
    appendonly yes